using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

/// <summary>
/// Main menu logic (scene "MainMenu", component on the UI canvas root). The UI
/// hierarchy is AUTHORED IN THE SCENE (first generated by Tools/CPU 100/Build Main
/// Menu Scene, then freely hand-editable / re-skinnable) - this component only
/// wires buttons, the volume slider and the mute toggle, and applies audio
/// settings. Volume/mute persist via PlayerPrefs and drive AudioListener.volume,
/// which is process-wide and therefore carries into every level loaded from here.
/// </summary>
public class MainMenuUI : MonoBehaviour
{
    [Header("Scene refs (wired by the builder; name-based fallback in Awake)")]
    public Button startButton;          // "StartButton"
    public Button levelsButton;         // "LevelsButton"
    public Button quitButton;           // "QuitButton"
    public Button muteButton;           // "MuteButton"
    public Button backButton;           // "BackButton"
    public Button level1Button;         // "Level1"
    public Button level2Button;         // "Level2"
    public Button level3Button;         // "Level3"
    public Slider volumeSlider;         // "VolumeSlider"
    public Text muteLabel;              // Text under MuteButton
    public GameObject levelPanel;       // "LevelPanel", starts inactive

    [Header("Audio")]
    public AudioClip menuMusic;         // stage1 loop
    public AudioClip clickSfx;          // Mouse_Click
    public AudioClip startSfx;          // MainMenu/start.wav

    [Header("Scenes")]
    public string level1Scene = "Lvl_01";
    public string level2Scene = "Lvl_02";
    public string level3Scene = "Lvl_03";

    const string VolumePref = "cpu100_volume";
    const string MutePref = "cpu100_muted";

    AudioSource audioSource;
    bool muted;
    float volume = 0.8f;

    void Awake()
    {
        FindMissingRefs();
        EnsureScrollingTitle();

        volume = PlayerPrefs.GetFloat(VolumePref, 0.8f);
        muted = PlayerPrefs.GetInt(MutePref, 0) == 1;
        ApplyAudioSettings();

        audioSource = gameObject.AddComponent<AudioSource>();
        audioSource.playOnAwake = false;
        audioSource.spatialBlend = 0f;
        if (menuMusic != null)
        {
            audioSource.clip = menuMusic;
            audioSource.loop = true;
            audioSource.volume = 0.55f;
            audioSource.Play();
        }

        Wire(startButton, HandleStartClicked);
        Wire(levelsButton, HandleLevelsClicked);
        Wire(quitButton, HandleQuitClicked);
        Wire(muteButton, HandleMuteClicked);
        Wire(backButton, HandleBackClicked);
        Wire(level1Button, () => LoadLevel(level1Scene));
        Wire(level2Button, () => LoadLevel(level2Scene));
        Wire(level3Button, () => LoadLevel(level3Scene));

        if (volumeSlider != null)
        {
            volumeSlider.SetValueWithoutNotify(volume);
            volumeSlider.onValueChanged.AddListener(HandleVolumeChanged);
        }
        RefreshMuteLabel();
        if (levelPanel != null) levelPanel.SetActive(false);
    }

    void EnsureScrollingTitle()
    {
        Transform screen = FindRecursive(transform, "Screen");
        if (screen == null) return;

        MainMenuScrollingTitle scrollingTitle = screen.GetComponent<MainMenuScrollingTitle>();
        if (scrollingTitle == null)
            scrollingTitle = screen.gameObject.AddComponent<MainMenuScrollingTitle>();
        scrollingTitle.EnsureVisuals();
    }

    void FindMissingRefs()
    {
        if (startButton == null) startButton = FindComp<Button>("StartButton");
        if (levelsButton == null) levelsButton = FindComp<Button>("LevelsButton");
        if (quitButton == null) quitButton = FindComp<Button>("QuitButton");
        if (muteButton == null) muteButton = FindComp<Button>("MuteButton");
        if (backButton == null) backButton = FindComp<Button>("BackButton");
        if (level1Button == null) level1Button = FindComp<Button>("Level1");
        if (level2Button == null) level2Button = FindComp<Button>("Level2");
        if (level3Button == null) level3Button = FindComp<Button>("Level3");
        if (volumeSlider == null) volumeSlider = FindComp<Slider>("VolumeSlider");
        if (levelPanel == null)
        {
            Transform t = FindRecursive(transform, "LevelPanel");
            levelPanel = t != null ? t.gameObject : null;
        }
        if (muteLabel == null && muteButton != null)
            muteLabel = muteButton.GetComponentInChildren<Text>(true);
    }

    T FindComp<T>(string childName) where T : Component
    {
        Transform t = FindRecursive(transform, childName);
        return t != null ? t.GetComponent<T>() : null;
    }

    // Depth-first name search that also visits inactive children.
    static Transform FindRecursive(Transform root, string childName)
    {
        for (int i = 0; i < root.childCount; i++)
        {
            Transform child = root.GetChild(i);
            if (child.name == childName) return child;
            Transform deep = FindRecursive(child, childName);
            if (deep != null) return deep;
        }
        return null;
    }

    void Wire(Button button, UnityEngine.Events.UnityAction action)
    {
        if (button == null) return;
        button.onClick.AddListener(PlayClick);
        button.onClick.AddListener(action);
    }

    // ---------------- Handlers ----------------

    void HandleStartClicked()
    {
        StartCoroutine(LoadAfterSfx(level1Scene, startSfx));
    }

    void HandleLevelsClicked()
    {
        if (levelPanel == null) return;
        levelPanel.SetActive(true);
        levelPanel.transform.SetAsLastSibling();
    }

    void HandleBackClicked()
    {
        if (levelPanel != null) levelPanel.SetActive(false);
    }

    void HandleQuitClicked()
    {
#if UNITY_EDITOR
        UnityEditor.EditorApplication.isPlaying = false;
#else
        Application.Quit();
#endif
    }

    void LoadLevel(string sceneName)
    {
        StartCoroutine(LoadAfterSfx(sceneName, startSfx));
    }

    IEnumerator LoadAfterSfx(string sceneName, AudioClip sfx)
    {
        if (sfx != null && audioSource != null)
        {
            audioSource.PlayOneShot(sfx, 0.9f);
            yield return new WaitForSecondsRealtime(0.25f);
        }
        SceneManager.LoadScene(sceneName);
    }

    void HandleVolumeChanged(float value)
    {
        volume = value;
        PlayerPrefs.SetFloat(VolumePref, volume);
        ApplyAudioSettings();
    }

    void HandleMuteClicked()
    {
        muted = !muted;
        PlayerPrefs.SetInt(MutePref, muted ? 1 : 0);
        ApplyAudioSettings();
        RefreshMuteLabel();
    }

    void RefreshMuteLabel()
    {
        if (muteLabel != null) muteLabel.text = muted ? "SOUND: OFF" : "SOUND: ON";
    }

    void PlayClick()
    {
        if (audioSource != null && clickSfx != null)
            audioSource.PlayOneShot(clickSfx, 0.8f);
    }

    // AudioListener.volume is a process-wide static, so it carries into every level
    // loaded from here.
    void ApplyAudioSettings()
    {
        AudioListener.volume = muted ? 0f : volume;
    }
}
